// <auto-generated />
namespace ComputerStoreFinal.DataContexts.ComputerStoreMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IsThisLove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsThisLove));
        
        string IMigrationMetadata.Id
        {
            get { return "201412082055022_IsThisLove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
